# Generated by Django 3.1.7 on 2021-03-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('FFTS', '0001_initial'),
  ]

  operations = [
    migrations.AlterField(
      model_name='project',
      name='source_array',
      field=models.CharField(default='null', max_length=1024, verbose_name='Source'),
    ),
    migrations.AlterField(
      model_name='project',
      name='source_dir',
      field=models.CharField(default='null', max_length=256, verbose_name='Source DIR'),
    ),
  ]
