# Generated by Django 3.1.7 on 2021-03-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFTS', '0006_auto_20210304_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='business_flow',
            field=models.CharField(help_text='e.g.: BU_SRC_TO_DEST_UAT', max_length=33, verbose_name='Business Flow'),
        ),
    ]
