# Generated by Django 3.1.7 on 2021-03-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFTS', '0010_auto_20210304_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ffts_id',
            field=models.CharField(default='AUTO-GENERATION', max_length=47, verbose_name='FFTS ID'),
        ),
    ]
