# Generated by Django 3.1.7 on 2021-03-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('FFTS', '0018_auto_20210305_0014'),
  ]

  operations = [
    migrations.AlterField(
      model_name='project',
      name='strategy',
      field=models.CharField(choices=[('Polling', 'Polling'), ('Trigger', 'Trigger'), ('Initialization', 'Initialization')], max_length=15,
                             verbose_name='Strategy'),
    ),
  ]
