# Generated by Django 3.1.7 on 2021-02-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210228_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sync_config',
            field=models.CharField(default='N', max_length=3, verbose_name='sync_config'),
        ),
    ]
